import art
from art import *
import sys
from art import text2art as tx
from art import tprint as tp
import webbrowser

print (""""\033[2;35m
==========================================================                                                
||                                                      ||
|| .d8888b.    88d8b.d8b. .d8888b. 88d888b. dP    dP    ||
|| 88'  `""    88'`88'`88 88ooood8 88'  `88 88    88    ||
|| 88.  ...    88  88  88 88.  ... 88    88 88.  .88    ||
|| `88888P'    dP  dP  dP `88888P' dP    dP `88888P'    ||
=========================================================
=========================================================
||Note :                                                ||
||If you are running with an Android/ios mobile device  ||
||use in landscape mode for a better experience         ||
=========================================================
=========================================================
||SUPPORT                                               ||
==========+++++++++++++++++++++++++++++++++++++==========
||Maintainer[*] : shade234sherif                        ||
||Team[*] : Alone                                       ||
||Git[*]: shade234sherif                                ||
||Wa.me[*] : +2349155558315                             ||
||Facebook page[*] : https://facebook.com/cyberhacks6   ||
||Join GC[*]: https://facebook.com/groups/shade234sherif|| 
||( ETHICAL HACKING FOR BEGINNERS - SHADE234SHERIF )    ||
||Sub Yt[*]: shade234sherif                             ||
||                                                      ||
==========================================================                                                                                          
\033[1;32m""")

print(randart())
print("")

choice = True
while choice:
    print("[1] Noun to art")
    print("[2] Text to art")
    print("[3] Text to morse")
    print("[4] Mood to art")
    print("[5] Exit")
    choice = input("Select option:")
    if choice =="1":
        noun = input("Noun here:")
        length = int(input("How many copies?"))
        at = art(noun, number=length)
        print(at)

    elif choice =="2":
        class font():
            # 108 fonts
            arte = input("Text here:")
            print("\033[2;0m \033[2;34m")
            Z = tx(arte, font='sanserif')
            print(Z)
            Z = tx(arte, font='small')
            print(Z)
            Z = tx(arte, font='bold')
            print(Z)
            Z = tx(arte, font='Bold')
            print(Z)
            Z = tx(arte, font='speed')
            print(Z)
            Z = tx(arte, font='linux')
            print(Z)
            Z = tx(arte, font='3-d')
            print(Z)
            Z = tx(arte, font='3x5')
            print(Z)
            Z = tx(arte, font='acrobatic')
            print(Z)
            Z = tx(arte, font='aligator')
            print(Z)
            Z = tx(arte, font='aligator2')
            print(Z)
            Z = tx(arte, font='bold')
            print(Z)
            Z = tx(arte, font='alphabet')
            print(Z)
            Z = tx(arte, font='avatar')
            print(Z)
            Z = tx(arte, font='banner')
            print(Z)
            Z = tx(arte, font='banner 3-d')
            print(Z)
            Z = tx(arte, font='banner3')
            print(Z)
            Z = tx(arte, font='banner4')
            print(Z)
            Z = tx(arte, font='barbwire')
            print(Z)
            Z = tx(arte, font='basic')
            print(Z)
            Z = tx(arte, font='bell')
            print(Z)
            Z = tx(arte, font='big')
            print(Z)
            Z = tx(arte, font='binary')
            print(Z)
            Z = tx(arte, font='block')
            print(Z)
            Z = tx(arte, font='bubble')
            print(Z)
            Z = tx(arte, font='catwalk')
            print(Z)
            Z = tx(arte, font='chunky')
            print(Z)
            Z = tx(arte, font='computer')
            print(Z)
            Z = tx(arte, font='contessa')
            print(Z)
            Z = tx(arte, font='cosmic')
            print(Z)
            Z = tx(arte, font='cricket')
            print(Z)
            Z = tx(arte, font='cursive')
            print(Z)
            Z = tx(arte, font='diamond')
            print(Z)
            Z = tx(arte, font='digital')
            print(Z)
            Z = tx(arte, font='doh')
            print(Z)
            Z = tx(arte, font='doom')
            print(Z)
            Z = tx(arte, font='dotmatrix')
            print(Z)
            Z = tx(arte, font='drpepper')
            print(Z)
            Z = tx(arte, font='efitchess')
            print(Z)
            Z = tx(arte, font='eftiwater')
            print(Z)
            Z = tx(arte, font='epic')
            print(Z)
            Z = tx(arte, font='fender')
            print(Z)
            Z = tx(arte, font='fuzzy')
            print(Z)
            Z = tx(arte, font='goofy')
            print(Z)
            Z = tx(arte, font='gothic')
            print(Z)
            Z = tx(arte, font='graffiti')
            print(Z)
            Z = tx(arte, font='hollywood')
            print(Z)
            Z = tx(arte, font='invita')
            print(Z)
            Z = tx(arte, font='isometric')
            print(Z)
            Z = tx(arte, font='isometric2')
            print(Z)
            Z = tx(arte, font='isometric3')
            print(Z)
            Z = tx(arte, font='isometric4')
            print(Z)
            Z = tx(arte, font='italic')
            print(Z)
            Z = tx(arte, font='jazmine')
            print(Z)
            Z = tx(arte, font='jerusalem')
            print(Z)
            Z = tx(arte, font='katakana')
            print(Z)
            Z = tx(arte, font='larry3d')
            print(Z)
            Z = tx(arte, font='lcd')
            print(Z)
            Z = tx(arte, font='letters')
            print(Z)
            Z = tx(arte, font='linux')
            print(Z)
            Z = tx(arte, font='madrid')
            print(Z)
            Z = tx(arte, font='marquee')
            print(Z)
            Z = tx(arte, font='mike')
            print(Z)
            Z = tx(arte, font='mini')
            print(Z)
            Z = tx(arte, font='mirror')
            print(Z)
            Z = tx(arte, font='mnemonic')
            print(Z)
            Z = tx(arte, font='moscow')
            print(Z)
            Z = tx(arte, font='nipples')
            print(Z)
            Z = tx(arte, font='ntgreek')
            print(Z)
            Z = tx(arte, font='o8')
            print(Z)
            Z = tx(arte, font='ogre')
            print(Z)
            Z = tx(arte, font='peaks')
            print(Z)
            Z = tx(arte, font='pebbles')
            print(Z)
            Z = tx(arte, font='pepper')
            print(Z)
            Z = tx(arte, font='poison')
            print(Z)
            Z = tx(arte, font='poison')
            print(Z)
            Z = tx(arte, font='pyramid')
            print(Z)
            Z = tx(arte, font='relief')
            print(Z)
            Z = tx(arte, font='relief2')
            print(Z)
            Z = tx(arte, font='rev')
            print(Z)
            Z = tx(arte, font='rot13')
            print(Z)
            Z = tx(arte, font='rounded')
            print(Z)
            Z = tx(arte, font='runic')
            print(Z)
            Z = tx(arte, font='script')
            print(Z)
            Z = tx(arte, font='serifcap')
            print(Z)
            Z = tx(arte, font='shadow')
            print(Z)
            Z = tx(arte, font='rowancap')
            print(Z)
            Z = tx(arte, font='short')
            print(Z)
            Z = tx(arte, font='slant')
            print(Z)
            Z = tx(arte, font='slide')
            print(Z)
            Z = tx(arte, font='slscript')
            print(Z)
            Z = tx(arte, font='small')
            print(Z)
            Z = tx(arte, font='smisome1')
            print(Z)
            Z = tx(arte, font='smkeyboard')
            print(Z)
            Z = tx(arte, font='smscript')
            print(Z)
            Z = tx(arte, font='smshadow')
            print(Z)
            Z = tx(arte, font='smslant')
            print(Z)
            Z = tx(arte, font='smtengwar')
            print(Z)
            Z = tx(arte, font='speed')
            print(Z)
            Z = tx(arte, font='stampello')
            print(Z)
            Z = tx(arte, font='standard')
            print(Z)
            Z = tx(arte, font='starwars')
            print(Z)
            Z = tx(arte, font='stellar')
            print(Z)
            Z = tx(arte, font='stop')
            print(Z)
            Z = tx(arte, font='straight')
            print(Z)
            Z = tx(arte, font='tanja')
            print(Z)
            Z = tx(arte, font='tengwar')
            print(Z)
            Z = tx(arte, font='term')
            print(Z)
            Z = tx(arte, font='thick')
            print(Z)
            Z = tx(arte, font='thin')
            print(Z)
            Z = tx(arte, font='thick')
            print(Z)
            Z = tx(arte, font='threepoint')
            print(Z)
            Z = tx(arte, font='ticks')
            print(Z)
            Z = tx(arte, font='tickslant')
            print(Z)
            Z = tx(arte, font='tinkertoy')
            print(Z)
            Z = tx(arte, font='tombstone')
            print(Z)
            Z = tx(arte, font='trek')
            print(Z)
            Z = tx(arte, font='tsalagi')
            print(Z)
            Z = tx(arte, font='twopoint')
            print(Z)
            Z = tx(arte, font='univers')
            print(Z)
            Z = tx(arte, font='usaflag')
            print(Z)
            Z = tx(arte, font='wavy')
            print(Z)
            Z = tx(arte, font='weird')
            print(Z)
            print("")
            print("")
            print(randart())
            print("finished")

    elif choice == "3":
        texte = input("Text here:")
        X = tx(texte, font='moose')
        print(X)

    elif choice == "4":
        mode = input("Mood?")
        aprint(mode)

    elif choice == "5":
        print("\033[2;31m bye\033[2;0m")
        sys.exit()
    elif choice != "":
        print("\033[1;31mINVALID OPTION\033[1;32m")




